language: python
sudo: true

python:
  - 3.6

matrix:
  fast_finish: true


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libpq-dev libssl-dev openssl libffi-dev zlib1g-dev
  - sudo apt-get install -y libmysqlclient-dev git python3-gi python3-dbus upx-ucl libperl-dev
  - sudo apt-get install gir1.2-gtk-3.0 python3-gi python3-gi-cairo xauth xvfb
#  libgtk2.0-dev gobject-introspection libgirepository1.0-dev pkg-config libdbus-1-3


  - wget https://launchpad.net/~jonathonf/+archive/ubuntu/gtk3.18/+build/10651703/+files/libgirepository-1.0-1_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb
  - sudo dpkg -i libgirepository-1.0-1_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb

  - wget https://launchpad.net/~jonathonf/+archive/ubuntu/gtk3.18/+build/10651703/+files/gir1.2-glib-2.0_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb
  - sudo dpkg -i gir1.2-glib-2.0_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb

  - wget https://launchpad.net/~jonathonf/+archive/ubuntu/gtk3.18/+build/10651703/+files/gir1.2-freedesktop_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb
  - dpkg -i dpkg -i gir1.2-freedesktop_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb 

  - wget https://launchpad.net/~jonathonf/+archive/ubuntu/gtk3.18/+build/10651703/+files/gobject-introspection_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb
  - sudo dpkg -i gobject-introspection_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb

  - wget https://launchpad.net/~jonathonf/+archive/ubuntu/gtk3.18/+build/10651703/+files/libgirepository1.0-dev_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb
  - sudo dpkg -i libgirepository1.0-dev_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb


#  - wget https://launchpad.net/~jonathonf/+archive/ubuntu/gtk3.18/+build/10651703/+files/gir1.2-freedesktop_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb
#  - sudo dpkg -i gir1.2-freedesktop_1.46.0-3ubuntu1~ubuntu14.04.1york0_i386.deb

install:
  - pip install -r requirements.txt

script:
  - make lint
  - make build

#  after_success:
#      - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: releases
  api_key:
    secure: "g7USjPc5LsR7eKPS8noK7wTVIwANN1vkeVQN7rTdoQsrJoCWS544Flm0iWkePmVsVgx45ei2nJvn+FvEeQ8j8Ro/tZzmRjdn+e84QEIcKkWh2cgRlNN2PTUD+0L4D1G476vkQ/c66+rtlaFvhkZud7FQufQUdsB5QnT2uZLkwO/g9bxHiHgyqTCo/+PsmFpDl47kD3dzYIXESfFNVtfEwEot6NmN+3fDLw5kKlzeVzgqPRQIAxof8OmjTeaRTv5aG36cWeVmN/+mZyUlkdt4cXziRDOYPi7KrEnL+BKEp/dx1G7P0pDwTo4o0f75bjfi/MGmQadnE9/TAVUud9XpBi9RgBiq0tk5sha0L8Ds4usWUnDjf1cVYxn9vLT1OIeLwPqS5YxlV+7ahQ2wTlUNew4FXL3/gtTO9WAP8Gy8KDzVy+LX1tGRkuGxjDZx7Diwts557cV3PlOajuhJDBDFE17gvpnrJ7KRQ2Dw8BKOpYqCK4V7WI56uNFPNylgXzH25LIGdMWFo4YZtQ/LhdjUZ7s4mPe8IvUCfgw9vy3FbhWK2osK21+7P+ZgmNITHlaEmiKsdct5txwOb53lx6o0AARtKH7mzPFkTdwlbu4qXBvd7STnNu4R6bLMG3lJWTE+22ZtAylHQKCC9Z4CnQLes2ITAHf7HnWgwC2LLwFYLSc="
  file:
    - dist/linux/lastseen
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: true
